name:  Bug Report
description: Informar sobre un error o comportamiento inesperado
title: "[BUG] Descripci贸n breve del problema"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: "Gracias por tomarte el tiempo de reportar este problema. Por favor, completa los siguientes campos."
  - type: textarea
    id: descripcion-bug
    attributes:
      label: Descripci贸n del Bug
      description: Explica claramente qu茅 sucede, incluyendo el comportamiento que esperabas.
      placeholder: Describe el problema detalladamente.
    validations:
      required: true
  - type: textarea
    id: pasos-reproducir
    attributes:
      label: Pasos para Reproducir
      description: Lista los pasos necesarios para que nosotros tambi茅n podamos ver el error.
      placeholder: |
        1. Ir a '...'
        2. Clic en '....'
        3. Scroll hacia '....'
        4. Ver error
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Versi贸n de UVLHub
      description: 驴En qu茅 versi贸n del proyecto encontraste el problema?
      options:
        - "v1.0.0 (Latest)"
        - "v0.9.0"
        - "Otro (especificar en la descripci贸n)"
    validations:
      required: true
  - type: checkboxes
    id: terminos
    attributes:
      label: Checklist
      options:
        - label: He buscado en Issues existentes y no encontr茅 un reporte similar.
          required: true
