"""empty message

Revision ID: 002
Revises: 001
Create Date: 2025-12-13 18:51:43.936693

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "002"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.add_column(sa.Column("slug", sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column("logo_url", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("website", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("is_public", sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ["slug"])

    with op.batch_alter_table("dataset_community_submission", schema=None) as batch_op:
        batch_op.add_column(sa.Column("submitter_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("message", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("feedback", sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, "user", ["submitter_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset_community_submission", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("feedback")
        batch_op.drop_column("message")
        batch_op.drop_column("submitter_id")

    with op.batch_alter_table("community", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("is_public")
        batch_op.drop_column("website")
        batch_op.drop_column("logo_url")
        batch_op.drop_column("slug")

    # ### end Alembic commands ###
